FROM eclipse-mosquitto:2

CMD ["sh", "-c", "mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log && mosquitto_passwd -b -c /mosquitto/config/passwordfile ${MOSQUITTO_USERNAME:-backend} ${MOSQUITTO_PASSWORD:-backend123} && exec mosquitto -c /mosquitto/config/mosquitto.conf"]
