FROM eclipse-mosquitto:2

CMD ["sh", "-c", "mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log && rm -f /mosquitto/config/passwordfile* && mosquitto_passwd -b -c /mosquitto/config/passwordfile ${MOSQUITTO_USERNAME:-backend} ${MOSQUITTO_PASSWORD:-backend123} && chown mosquitto:mosquitto /mosquitto/config/passwordfile && chmod 0700 /mosquitto/config/passwordfile && exec mosquitto -c /mosquitto/config/mosquitto.conf"]
